# Copyright (c) 2022-2025, The Isaac Lab Project Developers (https://github.com/isaac-sim/IsaacLab/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause


# Shadow Hand环境的SKRL前馈PPO算法配置文件。
# 该配置文件定义了使用SKRL库训练Shadow Hand环境的PPO算法参数，使用前馈网络结构。


# 随机种子
seed: 42


# 模型配置（使用skrl的模型实例化工具）
# https://skrl.readthedocs.io/en/latest/api/utils/model_instantiators.html
models:
  # 是否使用分离的网络
  separate: True
  
  # 策略网络配置（参见gaussian_model参数）
  policy:
    class: GaussianMixin  # 高斯混合类
    clip_actions: False  # 是否裁剪动作
    clip_log_std: True  # 是否裁剪对数标准差
    min_log_std: -20.0  # 最小对数标准差
    max_log_std: 2.0  # 最大对数标准差
    initial_log_std: 0.0  # 初始化对数标准差
    network:
      - name: net  # 网络名称
        input: STATES  # 输入：状态
        layers: [400, 400, 200, 100]  # 网络层单元数（前馈网络结构）
        activations: elu  # 激活函数
    output: ACTIONS  # 输出：动作
  
  # 价值网络配置（参见deterministic_model参数）
  value:
    class: DeterministicMixin  # 确定性混合类
    clip_actions: False  # 是否裁剪动作
    network:
      - name: net  # 网络名称
        input: STATES  # 输入：状态
        layers: [512, 512, 256, 128]  # 网络层单元数
        activations: elu  # 激活函数
    output: ONE  # 输出：单一值


# 回放缓冲区配置
# https://skrl.readthedocs.io/en/latest/api/memories/random.html
memory:
  class: RandomMemory  # 随机内存类
  memory_size: -1  # 内存大小（自动确定，与agent:rollouts相同）


# PPO智能体配置（字段名来自PPO_DEFAULT_CONFIG）
# https://skrl.readthedocs.io/en/latest/api/agents/ppo.html
agent:
  class: PPO  # PPO算法类
  rollouts: 16  # 回滚步数
  learning_epochs: 4  # 学习轮数
  mini_batches: 4  # 小批量数量
  discount_factor: 0.99  # 折扣因子
  lambda: 0.95  # GAE参数
  learning_rate: 5.0e-04  # 学习率
  learning_rate_scheduler: KLAdaptiveLR  # 学习率调度器
  learning_rate_scheduler_kwargs:
    kl_threshold: 0.01  # KL散度阈值
  state_preprocessor: RunningStandardScaler  # 状态预处理器
  state_preprocessor_kwargs: null  # 状态预处理器参数
  value_preprocessor: RunningStandardScaler  # 价值预处理器
  value_preprocessor_kwargs: null  # 价值预处理器参数
  random_timesteps: 0  # 随机时间步数
  learning_starts: 0  # 学习开始时间步数
  grad_norm_clip: 1.0  # 梯度范数裁剪
  ratio_clip: 0.2  # 比率裁剪参数
  value_clip: 0.2  # 价值裁剪参数
  clip_predicted_values: True  # 是否裁剪预测值
  entropy_loss_scale: 0.005  # 熵损失缩放
  value_loss_scale: 1.0  # 价值损失缩放
  kl_threshold: 0.0  # KL散度阈值
  rewards_shaper_scale: 1.0  # 奖励整形缩放
  time_limit_bootstrap: False  # 是否时间限制引导
  # 日志和检查点配置
  experiment:
    directory: "shadow_hand_openai_ff"  # 实验目录
    experiment_name: ""  # 实验名称
    write_interval: auto  # 写入间隔
    checkpoint_interval: auto  # 检查点间隔


# 顺序训练器配置
# https://skrl.readthedocs.io/en/latest/api/trainers/sequential.html
trainer:
  class: SequentialTrainer  # 顺序训练器类
  timesteps: 160000  # 训练时间步数
  environment_info: log  # 环境信息日志
